### PR TITLE
Improve PromptButtonTheme slightly

### PR DESCRIPTION
**Pull request by clragon**
This is a PR with some slight improvements.

- Added elevation to `PromptButtonTheme`
- Removed `ClipOval` in favour of `Material`'s `clipBehaviour` property
- Added `AppBarTheme`'s colors as default to the button, so it matches the AppBar
- Removed `cupertino.dart` dependency, as it is not needed
- Added a `didUpdateWidget` override, so the `PromptButtonTheme` updates on hot reload
- Refactored `child` inside the build method to closer match standard flutter practices

### CODE REVIEW

**Comment by NamanShergill** [comment]
Thanks for the PR, can you confirm if the changes in build method work fine with the widget being inside columns/ListViews? I was having an issue with rendering errors before I changed it, but it definitely felt like a hacky fix. If your setup doesn't have that issue that'll be great.

**Comment by clragon** [comment]
Could you explain what you mean by _inside_ Columns or ListViews?
I just tested it as a _Parent_ of a ListView and it seemed to work fine.

**Comment by NamanShergill** [comment]
> Could you explain what you mean by _inside_ Columns or ListViews? I just tested it as a _Parent_ of a ListView and it seemed to work fine.

Nevermind, it was a while ago so I had forgotten the exact issue, it was the widget having overflow errors due to the shrinkwrap property in the child listview, which I changed here https://github.com/NamanShergill/flutter_scroll_to_top/commit/fd41d54b6bc5e00454997d68821ceace69be8861.

I felt that issue shouldn't be handled by the library but the dev using it themselves. I did not publish that version because of this reason, so your implementation wouldn't break anything.

**Comment by NamanShergill** [comment]
I'll publish a new release to pub tomorrow, thank you!

**Comment by NamanShergill** [comment]
Just one question, is there any specific reason that [this](https://github.com/NamanShergill/flutter_scroll_to_top/blob/bea05fcfaacf6a60852e5db9d62f39b1a59934bd/lib/src/scroll_wrapper.dart#L175) is nullable?

**Comment by clragon** [comment]
I think originally I wanted to make it nullable and then set a default value inside the build method,
which I also did. But then I also set a default value inside the PromptTheme, so now its kinda useless again.

We could remove the default value in the prompt and let it be nullable,
or we could make it non-nullable and remove the default value in the build method.

**Comment by NamanShergill** [comment]
> I think originally I wanted to make it nullable and then set a default value inside the build method, which I also did. But then I also set a default value inside the PromptTheme, so now its kinda useless again.
> 
> We could remove the default value in the prompt and let it be nullable, or we could make it non-nullable and remove the default value in the build method.

No problem, I'll make it non nullable before making the release, just wanted to be sure it wasn't intended

**Comment by NamanShergill** [comment]
https://github.com/flutter/flutter/blob/18116933e77adc82f80866c928266a5b4f1ed645/packages/flutter/lib/src/widgets/container.dart#L384

Seems like setting widgets as variables is used by the framework itself too, we don't need it because we don't have to wrap it in other widgets so a function will serve the same purpose, but I believe there's not much performance difference between the two.

**Comment by NamanShergill** [comment]
I've set the elevation to be nullable and use the app bar elevation as the default instead of 0

**Comment by NamanShergill** [comment]
The new version is up

**Pull request merged**
